version: '3'
services:
  redis:
    image: redis
    container_name: cache
    ports:
    - 6379:6379
#    network_mode: host

  app:
    image: bigid:1.0
    ports:
    - 8081:3000
    links:
    - redis
#    network_mode: host
#    command: npm test

